#' Load conversion table for Vietnamese characters
#'
#' @return data.frame
#' @details
#' The table was adapted from \url{http://vietunicode.sourceforge.net/charset/}
#' @export
#'

loadEncodingTableVN <- function() {
  out <- structure(list(Unicode_Hex = c("U+00C0",
                                        "U+00C1", "U+00C2", "U+00C3", "U+00C8", "U+00C9", "U+00CA", "U+00CC",
                                        "U+00CD", "U+00D2", "U+00D3", "U+00D4", "U+00D5", "U+00D9", "U+00DA",
                                        "U+00DD", "U+00E0", "U+00E1", "U+00E2", "U+00E3", "U+00E8", "U+00E9",
                                        "U+00EA", "U+00EC", "U+00ED", "U+00F2", "U+00F3", "U+00F4", "U+00F5",
                                        "U+00F9", "U+00FA", "U+00FD", "U+0102", "U+0103", "U+0110", "U+0111",
                                        "U+0128", "U+0129", "U+0168", "U+0169", "U+01A0", "U+01A1", "U+01AF",
                                        "U+01B0", "U+1EA0", "U+1EA1", "U+1EA2", "U+1EA3", "U+1EA4", "U+1EA5",
                                        "U+1EA6", "U+1EA7", "U+1EA8", "U+1EA9", "U+1EAA", "U+1EAB", "U+1EAC",
                                        "U+1EAD", "U+1EAE", "U+1EAF", "U+1EB0", "U+1EB1", "U+1EB2", "U+1EB3",
                                        "U+1EB4", "U+1EB5", "U+1EB6", "U+1EB7", "U+1EB8", "U+1EB9", "U+1EBA",
                                        "U+1EBB", "U+1EBC", "U+1EBD", "U+1EBE", "U+1EBF", "U+1EC0", "U+1EC1",
                                        "U+1EC2", "U+1EC3", "U+1EC4", "U+1EC5", "U+1EC6", "U+1EC7", "U+1EC8",
                                        "U+1EC9", "U+1ECA", "U+1ECB", "U+1ECC", "U+1ECD", "U+1ECE", "U+1ECF",
                                        "U+1ED0", "U+1ED1", "U+1ED2", "U+1ED3", "U+1ED4", "U+1ED5", "U+1ED6",
                                        "U+1ED7", "U+1ED8", "U+1ED9", "U+1EDA", "U+1EDB", "U+1EDC", "U+1EDD",
                                        "U+1EDE", "U+1EDF", "U+1EE0", "U+1EE1", "U+1EE2", "U+1EE3", "U+1EE4",
                                        "U+1EE5", "U+1EE6", "U+1EE7", "U+1EE8", "U+1EE9", "U+1EEA", "U+1EEB",
                                        "U+1EEC", "U+1EED", "U+1EEE", "U+1EEF", "U+1EF0", "U+1EF1", "U+1EF2",
                                        "U+1EF3", "U+1EF4", "U+1EF5", "U+1EF6", "U+1EF7", "U+1EF8", "U+1EF9"
  ), VNI_Hex = c("41 D8", "41 D9", "41 C2", "41 D5", "45 D8", "45 D9",
                 "45 C2", "CC", "CD", "4F D8", "4F D9", "4F C2", "4F D5", "55 D8",
                 "55 D9", "59 D9", "61 F8", "61 F9", "61 E2", "61 F5", "65 F8",
                 "65 F9", "65 E2", "EC", "ED", "6F F8", "6F F9", "6F E2", "6F F5",
                 "75 F8", "75 F9", "79 F9", "41 CA", "61 EA", "D1", "F1", "D3",
                 "F3", "55 D5", "75 F5", "D4", "F4", "D6", "F6", "41 CF", "61 EF",
                 "41 DB", "61 FB", "41 C1", "61 E1", "41 C0", "61 E0", "41 C5",
                 "61 E5", "41 C3", "61 E3", "41 C4", "61 E4", "41 C9", "61 E9",
                 "41 C8", "61 E8", "41 DA", "61 FA", "41 DC", "61 FC", "41 CB",
                 "61 EB", "45 CF", "65 EF", "45 DB", "65 FB", "45 D5", "65 F5",
                 "45 C1", "65 E1", "45 C0", "65 E0", "45 C5", "65 E5", "45 C3",
                 "65 E3", "45 C4", "65 E4", "C6", "E6", "D2", "F2", "4F CF", "6F EF",
                 "4F DB", "6F FB", "4F C1", "6F E1", "4F C0", "6F E0", "4F C5",
                 "6F E5", "4F C3", "6F E3", "4F C4", "6F E4", "D4 D9", "F4 F9",
                 "D4 D8", "F4 F8", "D4 DB", "F4 FB", "D4 D5", "F4 F5", "D4 CF",
                 "F4 EF", "55 CF", "75 EF", "55 DB", "75 FB", "D6 D9", "F6 F9",
                 "D6 D8", "F6 F8", "D6 DB", "F6 FB", "D6 D5", "F6 F5", "D6 CF",
                 "F6 EF", "59 D8", "79 F8", "CE", "EE", "59 DB", "79 FB", "59 D5",
                 "79 F5"), VPS_Hex = c("80", "C1", "C2", "82", "D7", "C9", "CA",
                                       "B5", "B4", "BC", "B9", "D4", "BE", "A8", "DA", "DD", "E0", "E1",
                                       "E2", "E3", "E8", "E9", "EA", "EC", "ED", "F2", "F3", "F4", "F5",
                                       "F9", "FA", "9A", "88", "E6", "F1", "C7", "B8", "EF", "AC", "DB",
                                       "F7", "D6", "D0", "DC", "2", "E5", "81", "E4", "83", "C3", "84",
                                       "C0", "85", "C4", "1C", "C5", "3", "C6", "8D", "A1", "8E", "A2",
                                       "8F", "A3", "F0", "A4", "4", "A5", "5", "CB", "DE", "C8", "FE",
                                       "EB", "90", "89", "93", "8A", "94", "8B", "95", "CD", "6", "8C",
                                       "B7", "CC", "10", "CE", "11", "86", "BD", "D5", "96", "D3", "97",
                                       "D2", "98", "B0", "99", "87", "12", "B6", "9D", "A7", "9E", "A9",
                                       "9F", "AA", "A6", "AB", "13", "AE", "14", "F8", "D1", "FB", "AD",
                                       "D9", "AF", "D8", "B1", "BA", "1D", "BB", "15", "BF", "B2", "FF",
                                       "19", "9C", "FD", "9B", "B3", "CF"), VISCII_Hex = c("C0", "C1",
                                                                                           "C2", "C3", "C8", "C9", "CA", "CC", "CD", "D2", "D3", "D4", "A0",
                                                                                           "D9", "DA", "DD", "E0", "E1", "E2", "E3", "E8", "E9", "EA", "EC",
                                                                                           "ED", "F2", "F3", "F4", "F5", "F9", "FA", "FD", "C5", "E5", "D0",
                                                                                           "F0", "CE", "EE", "9D", "FB", "B4", "BD", "BF", "DF", "80", "D5",
                                                                                           "C4", "E4", "84", "A4", "85", "A5", "86", "A6", "6", "E7", "87",
                                                                                           "A7", "81", "A1", "82", "A2", "2", "C6", "5", "C7", "83", "A3",
                                                                                           "89", "A9", "CB", "EB", "88", "A8", "8A", "AA", "8B", "AB", "8C",
                                                                                           "AC", "8D", "AD", "8E", "AE", "9B", "EF", "98", "B8", "9A", "F7",
                                                                                           "99", "F6", "8F", "AF", "90", "B0", "91", "B1", "92", "B2", "93",
                                                                                           "B5", "95", "BE", "96", "B6", "97", "B7", "B3", "DE", "94", "FE",
                                                                                           "9E", "F8", "9C", "FC", "BA", "D1", "BB", "D7", "BC", "D8", "FF",
                                                                                           "E6", "B9", "F1", "9F", "CF", "1E", "DC", "14", "D6", "19", "DB"
                                       ), TCVN3_Hex = c("41 B5", "41 B8", "A2", "41 B7", "45 CC", "45 D0",
                                                        "A3", "49 D7", "49 DD", "4F DF", "4F E3", "A4", "4F E2", "55 EF",
                                                        "55 F3", "59 FD", "B5", "B8", "A9", "B7", "CC", "D0", "AA", "D7",
                                                        "DD", "DF", "E3", "AB", "E2", "EF", "F3", "FD", "A1", "A8", "A7",
                                                        "AE", "49 DC", "DC", "55 F2", "F2", "A5", "AC", "A6", "AD", "41 B9",
                                                        "B9", "41 B6", "B6", "A2 CA", "CA", "A2 C7", "C7", "A2 C8", "C8",
                                                        "A2 C9", "C9", "A2 CB", "CB", "A1 BE", "BE", "A1 BB", "BB", "A1 BC",
                                                        "BC", "A1 BD", "BD", "A1 C6", "C6", "45 D1", "D1", "45 CE", "CE",
                                                        "45 CF", "CF", "A3 D5", "D5", "A3 D2", "D2", "A3 D3", "D3", "A3 D4",
                                                        "D4", "A3 D6", "D6", "49 D8", "D8", "49 DE", "DE", "4F E4", "E4",
                                                        "4F E1", "E1", "A4 E8", "E8", "A4 E5", "E5", "A4 E6", "E6", "A4 E7",
                                                        "E7", "A4 E9", "E9", "A5 ED", "ED", "A5 EA", "EA", "A5 EB", "EB",
                                                        "A5 EC", "EC", "A5 EE", "EE", "55 F4", "F4", "55 F1", "F1", "A6 F8",
                                                        "F8", "A6 F5", "F5", "A6 F6", "F6", "A6 F7", "F7", "A6 F9", "F9",
                                                        "59 FA", "FA", "59 FE", "FE", "59 FB", "FB", "59 FC", "FC"),
  VIQR = c("A`", "A'", "A^", "A~", "E`", "E'", "E^", "I`",
           "I'", "O`", "O'", "O^", "O~", "U`", "U'", "Y'", "a`", "a'",
           "a^", "a~", "e`", "e'", "e^", "i`", "i'", "o`", "o'", "o^",
           "o~", "u`", "u'", "y'", "A(", "a(", "DD", "dd", "I~", "i~",
           "U~", "u~", "O+", "o+", "U+", "u+", "A.", "a.", "A?", "a?",
           "A^'", "a^'", "A^`", "a^`", "A^?", "a^?", "A^~", "a^~", "A^.",
           "a^.", "A('", "a('", "A(`", "a(`", "A(?", "a(?", "A(~", "a(~",
           "A(.", "a(.", "E.", "e.", "E?", "e?", "E~", "e~", "E^'",
           "e^'", "E^`", "e^`", "E^?", "e^?", "E^~", "e^~", "E^.", "e^.",
           "I?", "i?", "I.", "i.", "O.", "o.", "O?", "o?", "O^'", "o^'",
           "O^`", "o^`", "O^?", "o^?", "O^~", "o^~", "O^.", "o^.", "O+'",
           "o+'", "O+`", "o+`", "O+?", "o+?", "O+~", "o+~", "O+.", "o+.",
           "U.", "u.", "U?", "u?", "U+'", "u+'", "U+`", "u+`", "U+?",
           "u+?", "U+~", "u+~", "U+.", "u+.", "Y`", "y`", "Y.", "y.",
           "Y?", "y?", "Y~", "y~"), English_Name = c("LATIN CAPITAL LETTER A WITH GRAVE",
                                                     "LATIN CAPITAL LETTER A WITH ACUTE", "LATIN CAPITAL LETTER A WITH CIRCUMFLEX",
                                                     "LATIN CAPITAL LETTER A WITH TILDE", "LATIN CAPITAL LETTER E WITH GRAVE",
                                                     "LATIN CAPITAL LETTER E WITH ACUTE", "LATIN CAPITAL LETTER E WITH CIRCUMFLEX",
                                                     "LATIN CAPITAL LETTER I WITH GRAVE", "LATIN CAPITAL LETTER I WITH ACUTE",
                                                     "LATIN CAPITAL LETTER O WITH GRAVE", "LATIN CAPITAL LETTER O WITH ACUTE",
                                                     "LATIN CAPITAL LETTER O WITH CIRCUMFLEX", "LATIN CAPITAL LETTER O WITH TILDE",
                                                     "LATIN CAPITAL LETTER U WITH GRAVE", "LATIN CAPITAL LETTER U WITH ACUTE",
                                                     "LATIN CAPITAL LETTER Y WITH ACUTE", "LATIN SMALL LETTER A WITH GRAVE",
                                                     "LATIN SMALL LETTER A WITH ACUTE", "LATIN SMALL LETTER A WITH CIRCUMFLEX",
                                                     "LATIN SMALL LETTER A WITH TILDE", "LATIN SMALL LETTER E WITH GRAVE",
                                                     "LATIN SMALL LETTER E WITH ACUTE", "LATIN SMALL LETTER E WITH CIRCUMFLEX",
                                                     "LATIN SMALL LETTER I WITH GRAVE", "LATIN SMALL LETTER I WITH ACUTE",
                                                     "LATIN SMALL LETTER O WITH GRAVE", "LATIN SMALL LETTER O WITH ACUTE",
                                                     "LATIN SMALL LETTER O WITH CIRCUMFLEX", "LATIN SMALL LETTER O WITH TILDE",
                                                     "LATIN SMALL LETTER U WITH GRAVE", "LATIN SMALL LETTER U WITH ACUTE",
                                                     "LATIN SMALL LETTER Y WITH ACUTE", "LATIN CAPITAL LETTER A WITH BREVE",
                                                     "LATIN SMALL LETTER A WITH BREVE", "LATIN CAPITAL LETTER D WITH STROKE",
                                                     "LATIN SMALL LETTER D WITH STROKE", "LATIN CAPITAL LETTER I WITH TILDE",
                                                     "LATIN SMALL LETTER I WITH TILDE", "LATIN CAPITAL LETTER U WITH TILDE",
                                                     "LATIN SMALL LETTER U WITH TILDE", "LATIN CAPITAL LETTER O WITH HORN",
                                                     "LATIN SMALL LETTER O WITH HORN", "LATIN CAPITAL LETTER U WITH HORN",
                                                     "LATIN SMALL LETTER U WITH HORN", "LATIN CAPITAL LETTER A WITH DOT BELOW",
                                                     "LATIN SMALL LETTER A WITH DOT BELOW", "LATIN CAPITAL LETTER A WITH HOOK ABOVE",
                                                     "LATIN SMALL LETTER A WITH HOOK ABOVE", "LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND ACUTE",
                                                     "LATIN SMALL LETTER A WITH CIRCUMFLEX AND ACUTE", "LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND GRAVE",
                                                     "LATIN SMALL LETTER A WITH CIRCUMFLEX AND GRAVE", "LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE",
                                                     "LATIN SMALL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE", "LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND TILDE",
                                                     "LATIN SMALL LETTER A WITH CIRCUMFLEX AND TILDE", "LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND DOT BELOW",
                                                     "LATIN SMALL LETTER A WITH CIRCUMFLEX AND DOT BELOW", "LATIN CAPITAL LETTER A WITH BREVE AND ACUTE",
                                                     "LATIN SMALL LETTER A WITH BREVE AND ACUTE", "LATIN CAPITAL LETTER A WITH BREVE AND GRAVE",
                                                     "LATIN SMALL LETTER A WITH BREVE AND GRAVE", "LATIN CAPITAL LETTER A WITH BREVE AND HOOK ABOVE",
                                                     "LATIN SMALL LETTER A WITH BREVE AND HOOK ABOVE", "LATIN CAPITAL LETTER A WITH BREVE AND TILDE",
                                                     "LATIN SMALL LETTER A WITH BREVE AND TILDE", "LATIN CAPITAL LETTER A WITH BREVE AND DOT BELOW",
                                                     "LATIN SMALL LETTER A WITH BREVE AND DOT BELOW", "LATIN CAPITAL LETTER E WITH DOT BELOW",
                                                     "LATIN SMALL LETTER E WITH DOT BELOW", "LATIN CAPITAL LETTER E WITH HOOK ABOVE",
                                                     "LATIN SMALL LETTER E WITH HOOK ABOVE", "LATIN CAPITAL LETTER E WITH TILDE",
                                                     "LATIN SMALL LETTER E WITH TILDE", "LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND ACUTE",
                                                     "LATIN SMALL LETTER E WITH CIRCUMFLEX AND ACUTE", "LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND GRAVE",
                                                     "LATIN SMALL LETTER E WITH CIRCUMFLEX AND GRAVE", "LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE",
                                                     "LATIN SMALL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE", "LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND TILDE",
                                                     "LATIN SMALL LETTER E WITH CIRCUMFLEX AND TILDE", "LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND DOT BELOW",
                                                     "LATIN SMALL LETTER E WITH CIRCUMFLEX AND DOT BELOW", "LATIN CAPITAL LETTER I WITH HOOK ABOVE",
                                                     "LATIN SMALL LETTER I WITH HOOK ABOVE", "LATIN CAPITAL LETTER I WITH DOT BELOW",
                                                     "LATIN SMALL LETTER I WITH DOT BELOW", "LATIN CAPITAL LETTER O WITH DOT BELOW",
                                                     "LATIN SMALL LETTER O WITH DOT BELOW", "LATIN CAPITAL LETTER O WITH HOOK ABOVE",
                                                     "LATIN SMALL LETTER O WITH HOOK ABOVE", "LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND ACUTE",
                                                     "LATIN SMALL LETTER O WITH CIRCUMFLEX AND ACUTE", "LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND GRAVE",
                                                     "LATIN SMALL LETTER O WITH CIRCUMFLEX AND GRAVE", "LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE",
                                                     "LATIN SMALL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE", "LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND TILDE",
                                                     "LATIN SMALL LETTER O WITH CIRCUMFLEX AND TILDE", "LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND DOT BELOW",
                                                     "LATIN SMALL LETTER O WITH CIRCUMFLEX AND DOT BELOW", "LATIN CAPITAL LETTER O WITH HORN AND ACUTE",
                                                     "LATIN SMALL LETTER O WITH HORN AND ACUTE", "LATIN CAPITAL LETTER O WITH HORN AND GRAVE",
                                                     "LATIN SMALL LETTER O WITH HORN AND GRAVE", "LATIN CAPITAL LETTER O WITH HORN AND HOOK ABOVE",
                                                     "LATIN SMALL LETTER O WITH HORN AND HOOK ABOVE", "LATIN CAPITAL LETTER O WITH HORN AND TILDE",
                                                     "LATIN SMALL LETTER O WITH HORN AND TILDE", "LATIN CAPITAL LETTER O WITH HORN AND DOT BELOW",
                                                     "LATIN SMALL LETTER O WITH HORN AND DOT BELOW", "LATIN CAPITAL LETTER U WITH DOT BELOW",
                                                     "LATIN SMALL LETTER U WITH DOT BELOW", "LATIN CAPITAL LETTER U WITH HOOK ABOVE",
                                                     "LATIN SMALL LETTER U WITH HOOK ABOVE", "LATIN CAPITAL LETTER U WITH HORN AND ACUTE",
                                                     "LATIN SMALL LETTER U WITH HORN AND ACUTE", "LATIN CAPITAL LETTER U WITH HORN AND GRAVE",
                                                     "LATIN SMALL LETTER U WITH HORN AND GRAVE", "LATIN CAPITAL LETTER U WITH HORN AND HOOK ABOVE",
                                                     "LATIN SMALL LETTER U WITH HORN AND HOOK ABOVE", "LATIN CAPITAL LETTER U WITH HORN AND TILDE",
                                                     "LATIN SMALL LETTER U WITH HORN AND TILDE", "LATIN CAPITAL LETTER U WITH HORN AND DOT BELOW",
                                                     "LATIN SMALL LETTER U WITH HORN AND DOT BELOW", "LATIN CAPITAL LETTER Y WITH GRAVE",
                                                     "LATIN SMALL LETTER Y WITH GRAVE", "LATIN CAPITAL LETTER Y WITH DOT BELOW",
                                                     "LATIN SMALL LETTER Y WITH DOT BELOW", "LATIN CAPITAL LETTER Y WITH HOOK ABOVE",
                                                     "LATIN SMALL LETTER Y WITH HOOK ABOVE", "LATIN CAPITAL LETTER Y WITH TILDE",
                                                     "LATIN SMALL LETTER Y WITH TILDE"), ascii = c("A", "A", "A",
                                                                                                   "A", "E", "E", "E", "I", "I", "O", "O", "O", "O", "U", "U",
                                                                                                   "Y", "a", "a", "a", "a", "e", "e", "e", "i", "i", "o", "o",
                                                                                                   "o", "o", "u", "u", "y", "A", "a", "D", "d", "I", "i", "U",
                                                                                                   "u", "O", "o", "U", "u", "A", "a", "A", "a", "A", "a", "A",
                                                                                                   "a", "A", "a", "A", "a", "A", "a", "A", "a", "A", "a", "A",
                                                                                                   "a", "A", "a", "A", "a", "E", "e", "E", "e", "E", "e", "E",
                                                                                                   "e", "E", "e", "E", "e", "E", "e", "E", "e", "I", "i", "I",
                                                                                                   "i", "O", "o", "O", "o", "O", "o", "O", "o", "O", "o", "O",
                                                                                                   "o", "O", "o", "O", "o", "O", "o", "O", "o", "O", "o", "O",
                                                                                                   "o", "U", "u", "U", "u", "U", "u", "U", "u", "U", "u", "U",
                                                                                                   "u", "U", "u", "Y", "y", "Y", "y", "Y", "y", "Y", "y")), row.names = c(NA,
                                                                                                                                                                          -134L), class = "data.frame")  #out[,1] <- as_utf8(out[,1])


  out$Unicode <- intToUtf8(gsub("U+", "0x", out$Unicode_Hex, fixed = T), multiple = TRUE)

  out$VNI <- sapply(strsplit(out$VNI_Hex, " "), FUN = function(x) {
    intToUtf8(paste0("0x", x))})

  out$VPS <- sapply(strsplit(out$VPS_Hex, " "), FUN = function(x) {
    intToUtf8(paste0("0x", x))})

  out$VISCII <- sapply(strsplit(out$VISCII_Hex, " "), FUN = function(x) {
    intToUtf8(paste0("0x", x))})

  out$TCVN3 <- sapply(strsplit(out$TCVN3_Hex, " "), FUN = function(x) {
    intToUtf8(paste0("0x", x))})

  return(out)
}

